version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /opt/stacks/hass/hass-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    nodered:
      container_name: nodered
      image: nodered/node-red
      ports:
      - 1880:1880
      volumes:
      - /opt/stacks/hass/nodered:/data
      depends_on:
      - homeassistant
      - mosquitto
      environment:
      - TZ=Pacific/Auckland
      restart: unless-stopped
    mosquitto:
      image: eclipse-mosquitto
      container_name: mosquitto
      restart: unless-stopped
      ports:
      - 1883:1883
      - 9001:9001
      volumes:
      - "/opt/stacks/hass/mosquitto/config:/mosquitto/config"
      - "/opt/stacks/hass/mosquitto/data:/mosquitto/data"
      - "/opt/stacks/hass/mosquitto/log:/mosquitto/log"
      environment:
      - TZ=Pacific/Auckland
      user: "${PUID}:${PGID}" 
    hass-configurator:
      image: "causticlab/hass-configurator-docker:latest"
      restart: always
      ports:
      - "3218:3218/tcp"
      volumes:
      - "/opt/stacks/hass/configurator-config:/config"
      - "/opt/stacks/hass/hass-config:/hass-config"   